// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"25kxjhmd99","name":"LocationsCRUD","description":"","endpoint":"https://25kxjhmd99.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/Locations","/Locations/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:240e1c94-c2f7-4489-8458-ba703aaefb24',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'overwatchweb-hosting-mobilehub-631424005',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'de2ygfwpgx862.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"overwatchweb-mobilehub-631424005-Locations","attributes":[{"name":"userId","type":"S"},{"name":"itemId","type":"S"},{"name":"latitude","type":"N"},{"name":"longitude","type":"N"},{"name":"streamUrl","type":"S"},{"name":"time","type":"N"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"itemId"}],
    'aws_mobile_analytics_app_id': '907055e4a7d84de689cb2b72f6f0a841',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'cb74f19c-da1d-4ea9-9c59-519dea7fe2dd',
    'aws_project_name': 'overwatch-web',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'overwatchweb-deployments-mobilehub-631424005',
    'aws_resource_name_prefix': 'overwatchweb-mobilehub-631424005',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'overwatchweb-userfiles-mobilehub-631424005',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_VAwhrluwC',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '3hhhveteje0imho9629v6uplu8',
}

export default awsmobile;
